---
version: '3'
x-airflow-common:
  &airflow-common
  build:
    context: airflow
    args:
      AIRFLOW_IMAGE: apache/airflow:${AIRFLOW_VERSION}-python${AIRFLOW_PYTHON_VERSION}
      AIRFLOW_VERSION: ${AIRFLOW_VERSION}
      AIRFLOW_PYTHON_VERSION: ${AIRFLOW_PYTHON_VERSION}
      version: ${VERSION}
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_URL}
    AIRFLOW__CELERY__RESULT_BACKEND: db+${AIRFLOW_DB_URL}
    AIRFLOW__CELERY__BROKER_URL: ${AIRFLOW__CELERY__BROKER_URL}
    AIRFLOW__OPERATORS__DEFAULT_QUEUE: ${AIRFLOW__OPERATORS__DEFAULT_QUEUE}
    AIRFLOW__CELERY__CELERY_APP_NAME: ${AIRFLOW__CELERY__CELERY_APP_NAME}
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: '${AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION:-true}'
    AIRFLOW__CORE__LOAD_EXAMPLES: '${AIRFLOW__CORE__LOAD_EXAMPLES:-true}'
    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
    AIRFLOW_CONN_REDCAP_HSCN: '${AIRFLOW_CONN_REDCAP_HSCN}'
    AIRFLOW_CONN_IDENTITY: '${AIRFLOW_CONN_IDENTITY}'
    AIRFLOW_CONN_LIVE_DB: '${AIRFLOW_CONN_LIVE_DB}'
    AIRFLOW_CONN_DWH: '${AIRFLOW_CONN_DWH}'
    AIRFLOW_CONN_ETL_CENTRAL: '${AIRFLOW_CONN_ETL_CENTRAL}'
    AIRFLOW_VAR_ETL_DOWNLOAD_USERNAME: '${AIRFLOW_VAR_ETL_DOWNLOAD_USERNAME}'
    AIRFLOW_VAR_ETL_DOWNLOAD_PASSWORD: '${AIRFLOW_VAR_ETL_DOWNLOAD_PASSWORD}'
    AIRFLOW_VAR_ETL_ENCRYPTION_PASSWORD: '${AIRFLOW_VAR_ETL_ENCRYPTION_PASSWORD}'
    AIRFLOW_VAR_EDGE_USERNAME: '${AIRFLOW_VAR_EDGE_USERNAME}'
    AIRFLOW_VAR_EDGE_PASSWORD: '${AIRFLOW_VAR_EDGE_PASSWORD}'
    AIRFLOW_VAR_EDGE_BASE_URL: '${AIRFLOW_VAR_EDGE_BASE_URL}'
    AIRFLOW_VAR_CRFM_USERNAME: '${AIRFLOW_VAR_CRFM_USERNAME}'
    AIRFLOW_VAR_CRFM_PASSWORD: '${AIRFLOW_VAR_CRFM_PASSWORD}'
    AIRFLOW_VAR_CRFM_BASE_URL: '${AIRFLOW_VAR_CRFM_BASE_URL}'
    AIRFLOW__LOGGING__FAB_LOGGING_LEVEL: '${AIRFLOW__LOGGING__FAB_LOGGING_LEVEL:-ERROR}'
    SCHEDULE_LOAD_WAREHOUSE: '${SCHEDULE_LOAD_WAREHOUSE}'
    LBRC_SELENIUM_HOST: '${LBRC_SELENIUM_HOST}'
    LBRC_SELENIUM_DOWNLOAD_DIRECTORY: '/opt/airflow/downloads'
    AIRFLOW__SMTP__SMTP_HOST: '${AIRFLOW__SMTP__SMTP_HOST}'
    AIRFLOW__SMTP__SMTP_PORT: '${AIRFLOW__SMTP__SMTP_PORT}'
    AIRFLOW__SMTP__SMTP_USER: '${AIRFLOW__SMTP__SMTP_USER}'
    AIRFLOW__SMTP__SMTP_PASSWORD: '${AIRFLOW__SMTP__SMTP_PASSWORD}'
    AIRFLOW__SMTP__SMTP_MAIL_FROM: '${AIRFLOW__SMTP__SMTP_MAIL_FROM}'
    AIRFLOW__SMTP__SMTP_STARTTLS: 'False'
    AIRFLOW__SMTP__SMTP_SSL: 'False'
  volumes:
    - ${LOG_DIRECTORY}:/opt/airflow/logs
    - ${DAG_DIRECTORY}:/opt/airflow/dags
    - ${DOWNLOAD_DIRECTORY}:/opt/airflow/downloads
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"

services:
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - ${PORT}:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:${PORT}/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    ports:
      - 8793:8793
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'false'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD}
